name: Linting Checks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Check formatting
        # run prettier, then eslint, and then check if any files have changed
        run: |
          npm run format
          if [ -n "$(git diff --name-only --exit-code)" ]; then
            echo "There are changes to format"
            exit 1
          fi
      - name: Check linting
        run: npx eslint .
      - name: Check types
        run: npx tsc --noEmit
